# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: DIgCWSVulPldBjV6BCu6E5gbjRIvLWXZ
            client-secret: cUzBOHu8zichIkT7U9yXB4HO1kqsOb_rnaeiXlgoAhvBMbNOnaTNongopcgSswX7
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-myhmrcvh.us.auth0.com/